### ISSUE TITLE
How did you generate the video results in your demonstration? Is there any corresponding code that you can share?

### ISSUE THREAD

**Issue by wczxxy** [wangyxxjtu/AINet-Superpixel#1]

**Comment by wangyxxjtu** [comment]
Hi, I produced it frame by frame, which can be easily implemented by the released code. Please follow these steps: read video-> deocde to frames -> feed each frame into AINet -> cancatenate the results of all frames to produce videos.

**Comment by wczxxy** [comment]
Thanks for your reply, I will try to implement it!
